server {
    listen 80;
    server_name dipl.vizhu.su;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name dipl.vizhu.su;

    ssl_certificate     /etc/letsencrypt/live/dipl.vizhu.su/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/dipl.vizhu.su/privkey.pem;

    ssl_protocols     TLSv1.2 TLSv1.3;
    ssl_ciphers       HIGH:!aNULL:!MD5;
    ssl_session_cache shared:SSL:10m;

    add_header Strict-Transport-Security "max-age=31536000" always;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 200 'dipl.vizhu.su works';
        add_header Content-Type text/plain;
    }
}
